version: "3.9"

services:
  web:
    image: odoo:18.0
    depends_on:
      - db
      - nginx
      - n8n
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    env_file:
      - env/odoo.env
    command:

  db:
    image: postgres:17
    ports:
      - 5432:5432
    env_file:
      - env/postgresql.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./box18/odoo_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    tty: true

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=odoo
      - DB_POSTGRESDB_PASSWORD=odoo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n.tuankiet.media
      - WEBHOOK_URL=https://n8n.tuankiet.media/
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
    tty: true

volumes:
  odoo-web-data:
  odoo-db-data:
  n8n_data:
