from . import sale_order_sever_copy
from . import sale_order
from . import sale_order_line_inherit
from . import product_template_inherit
from . import deposit_confirm_wizard
from . import account_move_ext
from . import account_payment_register
from . import pancake_conversation
from . import page_fm_integration
from . import page_fm_conversation